package com.boc.model;
// Generated Sep 27, 2016 11:35:37 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AreaBranchMapping generated by hbm2java
 */
@Entity
@Table(name = "AREA_BRANCH_MAPPING", schema = "WFCONFIG", uniqueConstraints = @UniqueConstraint(columnNames = "BID") )
public class AreaBranchMapping implements java.io.Serializable {

	private int areaBrId;
	private BranchBase branchBase;
	private AreaBase areaBase;

	public AreaBranchMapping() {
	}

	public AreaBranchMapping(int areaBrId, BranchBase branchBase, AreaBase areaBase) {
		this.areaBrId = areaBrId;
		this.branchBase = branchBase;
		this.areaBase = areaBase;
	}

	@Id

	@Column(name = "AREA_BR_ID", unique = true, nullable = false)
	public int getAreaBrId() {
		return this.areaBrId;
	}

	public void setAreaBrId(int areaBrId) {
		this.areaBrId = areaBrId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BID", unique = true, nullable = false)
	public BranchBase getBranchBase() {
		return this.branchBase;
	}

	public void setBranchBase(BranchBase branchBase) {
		this.branchBase = branchBase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AID", nullable = false)
	public AreaBase getAreaBase() {
		return this.areaBase;
	}

	public void setAreaBase(AreaBase areaBase) {
		this.areaBase = areaBase;
	}

}
