package com.boc.model;
// Generated Jun 23, 2016 11:37:27 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductLoanDetails generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT_LOAN_DETAILS", schema = "WFCONFIG")
public class ProductLoanDetails implements java.io.Serializable {

	private int plid;
	private ProductBase productBase;
	private Integer maxRepaymentPeriod;
	private Integer minAge;
	private Integer maxAge;
	private BigDecimal interestRateFixed;
	private BigDecimal interestRateVariable1;
	private BigDecimal interestRateVariable2;
	private BigDecimal percentageOfGrossSalary;
	private BigDecimal percentageOfOtherIncome;
	private Double maxLoanAmount;

	public ProductLoanDetails() {
	}

	public ProductLoanDetails(int plid, ProductBase productBase) {
		this.plid = plid;
		this.productBase = productBase;
	}

	public ProductLoanDetails(int plid, ProductBase productBase, Integer maxRepaymentPeriod, Integer minAge,
			Integer maxAge, BigDecimal interestRateFixed, BigDecimal interestRateVariable1,
			BigDecimal interestRateVariable2, BigDecimal percentageOfGrossSalary, BigDecimal percentageOfOtherIncome,
			Double maxLoanAmount) {
		this.plid = plid;
		this.productBase = productBase;
		this.maxRepaymentPeriod = maxRepaymentPeriod;
		this.minAge = minAge;
		this.maxAge = maxAge;
		this.interestRateFixed = interestRateFixed;
		this.interestRateVariable1 = interestRateVariable1;
		this.interestRateVariable2 = interestRateVariable2;
		this.percentageOfGrossSalary = percentageOfGrossSalary;
		this.percentageOfOtherIncome = percentageOfOtherIncome;
		this.maxLoanAmount = maxLoanAmount;
	}

	@Id

	@Column(name = "PLID", unique = true, nullable = false)
	public int getPlid() {
		return this.plid;
	}

	public void setPlid(int plid) {
		this.plid = plid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PID", nullable = false)
	public ProductBase getProductBase() {
		return this.productBase;
	}

	public void setProductBase(ProductBase productBase) {
		this.productBase = productBase;
	}

	@Column(name = "MAX_REPAYMENT_PERIOD")
	public Integer getMaxRepaymentPeriod() {
		return this.maxRepaymentPeriod;
	}

	public void setMaxRepaymentPeriod(Integer maxRepaymentPeriod) {
		this.maxRepaymentPeriod = maxRepaymentPeriod;
	}

	@Column(name = "MIN_AGE")
	public Integer getMinAge() {
		return this.minAge;
	}

	public void setMinAge(Integer minAge) {
		this.minAge = minAge;
	}

	@Column(name = "MAX_AGE")
	public Integer getMaxAge() {
		return this.maxAge;
	}

	public void setMaxAge(Integer maxAge) {
		this.maxAge = maxAge;
	}

	@Column(name = "INTEREST_RATE_FIXED", precision = 6, scale = 4)
	public BigDecimal getInterestRateFixed() {
		return this.interestRateFixed;
	}

	public void setInterestRateFixed(BigDecimal interestRateFixed) {
		this.interestRateFixed = interestRateFixed;
	}

	@Column(name = "INTEREST_RATE_VARIABLE1", precision = 6, scale = 4)
	public BigDecimal getInterestRateVariable1() {
		return this.interestRateVariable1;
	}

	public void setInterestRateVariable1(BigDecimal interestRateVariable1) {
		this.interestRateVariable1 = interestRateVariable1;
	}

	@Column(name = "INTEREST_RATE_VARIABLE2", precision = 6, scale = 4)
	public BigDecimal getInterestRateVariable2() {
		return this.interestRateVariable2;
	}

	public void setInterestRateVariable2(BigDecimal interestRateVariable2) {
		this.interestRateVariable2 = interestRateVariable2;
	}

	@Column(name = "PERCENTAGE_OF_GROSS_SALARY", precision = 4)
	public BigDecimal getPercentageOfGrossSalary() {
		return this.percentageOfGrossSalary;
	}

	public void setPercentageOfGrossSalary(BigDecimal percentageOfGrossSalary) {
		this.percentageOfGrossSalary = percentageOfGrossSalary;
	}

	@Column(name = "PERCENTAGE_OF_OTHER_INCOME", precision = 4)
	public BigDecimal getPercentageOfOtherIncome() {
		return this.percentageOfOtherIncome;
	}

	public void setPercentageOfOtherIncome(BigDecimal percentageOfOtherIncome) {
		this.percentageOfOtherIncome = percentageOfOtherIncome;
	}

	@Column(name = "MAX_LOAN_AMOUNT", precision = 53, scale = 0)
	public Double getMaxLoanAmount() {
		return this.maxLoanAmount;
	}

	public void setMaxLoanAmount(Double maxLoanAmount) {
		this.maxLoanAmount = maxLoanAmount;
	}

}
