package com.boc.model;
// Generated Jun 10, 2016 11:13:38 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ProductBase generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT_BASE", schema = "WFCONFIG", uniqueConstraints = @UniqueConstraint(columnNames = {
		"WF_PRODUCT_CODE", "PRODUCT_NAME" }))
public class ProductBase implements java.io.Serializable {

	private int pid;
	private ProductCategoryBase productCategoryBase;
	private String productCode;
	private String wfProductCode;
	private String productName;
	private String productDescription;
	private Set<ProductDocumentChecklistMapping> productDocumentChecklistMappings = new HashSet<ProductDocumentChecklistMapping>(
			0);
	private Set<ProfessionProductMapping> professionProductMappings = new HashSet<ProfessionProductMapping>(0);
	private Set<ProductLoanDetails> productLoanDetailses = new HashSet<ProductLoanDetails>(0);

	public ProductBase() {
	}

	public ProductBase(int pid, String productCode, String wfProductCode, String productName) {
		this.pid = pid;
		this.productCode = productCode;
		this.wfProductCode = wfProductCode;
		this.productName = productName;
	}

	public ProductBase(int pid, ProductCategoryBase productCategoryBase, String productCode, String wfProductCode,
			String productName, String productDescription,
			Set<ProductDocumentChecklistMapping> productDocumentChecklistMappings,
			Set<ProfessionProductMapping> professionProductMappings, Set<ProductLoanDetails> productLoanDetailses) {
		this.pid = pid;
		this.productCategoryBase = productCategoryBase;
		this.productCode = productCode;
		this.wfProductCode = wfProductCode;
		this.productName = productName;
		this.productDescription = productDescription;
		this.productDocumentChecklistMappings = productDocumentChecklistMappings;
		this.professionProductMappings = professionProductMappings;
		this.productLoanDetailses = productLoanDetailses;
	}

	@Id

	@Column(name = "PID", unique = true, nullable = false)
	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_CATEGORY_ID")
	public ProductCategoryBase getProductCategoryBase() {
		return this.productCategoryBase;
	}

	public void setProductCategoryBase(ProductCategoryBase productCategoryBase) {
		this.productCategoryBase = productCategoryBase;
	}

	@Column(name = "PRODUCT_CODE", nullable = false, length = 5)
	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	@Column(name = "WF_PRODUCT_CODE", nullable = false, length = 5)
	public String getWfProductCode() {
		return this.wfProductCode;
	}

	public void setWfProductCode(String wfProductCode) {
		this.wfProductCode = wfProductCode;
	}

	@Column(name = "PRODUCT_NAME", nullable = false, length = 100)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "PRODUCT_DESCRIPTION", length = 200)
	public String getProductDescription() {
		return this.productDescription;
	}

	public void setProductDescription(String productDescription) {
		this.productDescription = productDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productBase")
	public Set<ProductDocumentChecklistMapping> getProductDocumentChecklistMappings() {
		return this.productDocumentChecklistMappings;
	}

	public void setProductDocumentChecklistMappings(
			Set<ProductDocumentChecklistMapping> productDocumentChecklistMappings) {
		this.productDocumentChecklistMappings = productDocumentChecklistMappings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productBase")
	public Set<ProfessionProductMapping> getProfessionProductMappings() {
		return this.professionProductMappings;
	}

	public void setProfessionProductMappings(Set<ProfessionProductMapping> professionProductMappings) {
		this.professionProductMappings = professionProductMappings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productBase")
	public Set<ProductLoanDetails> getProductLoanDetailses() {
		return this.productLoanDetailses;
	}

	public void setProductLoanDetailses(Set<ProductLoanDetails> productLoanDetailses) {
		this.productLoanDetailses = productLoanDetailses;
	}

}
