package com.boc.model;
// Generated Sep 27, 2016 11:35:37 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ProvinceBranchMapping generated by hbm2java
 */
@Entity
@Table(name = "PROVINCE_BRANCH_MAPPING", schema = "WFCONFIG", uniqueConstraints = @UniqueConstraint(columnNames = "BID") )
public class ProvinceBranchMapping implements java.io.Serializable {

	private int provinceBrId;
	private ProvinceBase provinceBase;
	private BranchBase branchBase;

	public ProvinceBranchMapping() {
	}

	public ProvinceBranchMapping(int provinceBrId, ProvinceBase provinceBase, BranchBase branchBase) {
		this.provinceBrId = provinceBrId;
		this.provinceBase = provinceBase;
		this.branchBase = branchBase;
	}

	@Id

	@Column(name = "PROVINCE_BR_ID", unique = true, nullable = false)
	public int getProvinceBrId() {
		return this.provinceBrId;
	}

	public void setProvinceBrId(int provinceBrId) {
		this.provinceBrId = provinceBrId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PID", nullable = false)
	public ProvinceBase getProvinceBase() {
		return this.provinceBase;
	}

	public void setProvinceBase(ProvinceBase provinceBase) {
		this.provinceBase = provinceBase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BID", unique = true, nullable = false)
	public BranchBase getBranchBase() {
		return this.branchBase;
	}

	public void setBranchBase(BranchBase branchBase) {
		this.branchBase = branchBase;
	}

}
