package com.boc.model;
// Generated Jul 29, 2016 11:14:54 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * RlcBranchMapping generated by hbm2java
 */
@Entity
@Table(name = "RLC_BRANCH_MAPPING", schema = "WFCONFIG", uniqueConstraints = @UniqueConstraint(columnNames = "BID") )
public class RlcBranchMapping implements java.io.Serializable {

	private int rlcBrId;
	private RlcBase rlcBase;
	private BranchBase branchBase;

	public RlcBranchMapping() {
	}

	public RlcBranchMapping(int rlcBrId, RlcBase rlcBase, BranchBase branchBase) {
		this.rlcBrId = rlcBrId;
		this.rlcBase = rlcBase;
		this.branchBase = branchBase;
	}

	@Id

	@Column(name = "RLC_BR_ID", unique = true, nullable = false)
	public int getRlcBrId() {
		return this.rlcBrId;
	}

	public void setRlcBrId(int rlcBrId) {
		this.rlcBrId = rlcBrId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RLC_ID", nullable = false)
	public RlcBase getRlcBase() {
		return this.rlcBase;
	}

	public void setRlcBase(RlcBase rlcBase) {
		this.rlcBase = rlcBase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BID", unique = true, nullable = false)
	public BranchBase getBranchBase() {
		return this.branchBase;
	}

	public void setBranchBase(BranchBase branchBase) {
		this.branchBase = branchBase;
	}

}
