package com.boc.model;
// Generated Jun 23, 2016 11:37:27 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SecurityTypeDocumentChecklistMapping generated by hbm2java
 */
@Entity
@Table(name = "SECURITY_TYPE_DOCUMENT_CHECKLIST_MAPPING", schema = "WFCONFIG")
public class SecurityTypeDocumentChecklistMapping implements java.io.Serializable {

	private int sdcid;
	private DocumentTypeBase documentTypeBase;
	private SecurityTypeBase securityTypeBase;
	private char scanRequired;
	private Character mandatory;

	public SecurityTypeDocumentChecklistMapping() {
	}

	public SecurityTypeDocumentChecklistMapping(int sdcid, DocumentTypeBase documentTypeBase,
			SecurityTypeBase securityTypeBase, char scanRequired) {
		this.sdcid = sdcid;
		this.documentTypeBase = documentTypeBase;
		this.securityTypeBase = securityTypeBase;
		this.scanRequired = scanRequired;
	}

	public SecurityTypeDocumentChecklistMapping(int sdcid, DocumentTypeBase documentTypeBase,
			SecurityTypeBase securityTypeBase, char scanRequired, Character mandatory) {
		this.sdcid = sdcid;
		this.documentTypeBase = documentTypeBase;
		this.securityTypeBase = securityTypeBase;
		this.scanRequired = scanRequired;
		this.mandatory = mandatory;
	}

	@Id

	@Column(name = "SDCID", unique = true, nullable = false)
	public int getSdcid() {
		return this.sdcid;
	}

	public void setSdcid(int sdcid) {
		this.sdcid = sdcid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOCUMENT_ID", nullable = false)
	public DocumentTypeBase getDocumentTypeBase() {
		return this.documentTypeBase;
	}

	public void setDocumentTypeBase(DocumentTypeBase documentTypeBase) {
		this.documentTypeBase = documentTypeBase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SECURITY_TYPE_ID", nullable = false)
	public SecurityTypeBase getSecurityTypeBase() {
		return this.securityTypeBase;
	}

	public void setSecurityTypeBase(SecurityTypeBase securityTypeBase) {
		this.securityTypeBase = securityTypeBase;
	}

	@Column(name = "SCAN_REQUIRED", nullable = false, length = 1)
	public char getScanRequired() {
		return this.scanRequired;
	}

	public void setScanRequired(char scanRequired) {
		this.scanRequired = scanRequired;
	}

	@Column(name = "MANDATORY", length = 1)
	public Character getMandatory() {
		return this.mandatory;
	}

	public void setMandatory(Character mandatory) {
		this.mandatory = mandatory;
	}

}
