package com.boc.model;
// Generated Dec 8, 2016 4:00:33 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserRoleProductCategoryMapping generated by hbm2java
 */
@Entity
@Table(name = "USER_ROLE_PRODUCT_CATEGORY_MAPPING", schema = "WFCONFIG")
public class UserRoleProductCategoryMapping implements java.io.Serializable {

	private int urpcid;
	private int uid;
	private int rid;
	private int productCategoryId;
	private Short editflag;
	private Short deleteflag;

	public UserRoleProductCategoryMapping() {
	}

	public UserRoleProductCategoryMapping(int urpcid, int uid, int rid, int productCategoryId) {
		this.urpcid = urpcid;
		this.uid = uid;
		this.rid = rid;
		this.productCategoryId = productCategoryId;
	}

	public UserRoleProductCategoryMapping(int urpcid, int uid, int rid, int productCategoryId, Short editflag,
			Short deleteflag) {
		this.urpcid = urpcid;
		this.uid = uid;
		this.rid = rid;
		this.productCategoryId = productCategoryId;
		this.editflag = editflag;
		this.deleteflag = deleteflag;
	}
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Id

	@Column(name = "URPCID", unique = true, nullable = false)
	public int getUrpcid() {
		return this.urpcid;
	}

	public void setUrpcid(int urpcid) {
		this.urpcid = urpcid;
	}

	@Column(name = "UID", nullable = false)
	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	@Column(name = "RID", nullable = false)
	public int getRid() {
		return this.rid;
	}

	public void setRid(int rid) {
		this.rid = rid;
	}

	@Column(name = "PRODUCT_CATEGORY_ID", nullable = false)
	public int getProductCategoryId() {
		return this.productCategoryId;
	}

	public void setProductCategoryId(int productCategoryId) {
		this.productCategoryId = productCategoryId;
	}

	@Column(name = "EDITFLAG")
	public Short getEditflag() {
		return this.editflag;
	}

	public void setEditflag(Short editflag) {
		this.editflag = editflag;
	}

	@Column(name = "DELETEFLAG")
	public Short getDeleteflag() {
		return this.deleteflag;
	}

	public void setDeleteflag(Short deleteflag) {
		this.deleteflag = deleteflag;
	}

}
