package com.boc.model;
// Generated Dec 8, 2016 4:00:33 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserRoleProductCategoryBranchMapping generated by hbm2java
 */
@Entity
@Table(name = "USER_ROLE_PRODUCT_CATEGORY_BRANCH_MAPPING", schema = "WFCONFIG")
public class UserRoleProductCategoryBranchMapping implements java.io.Serializable {

	private int urpcbid;
	private int urpcid;
	private int bid;
	private Short editflag;
	private Short deleteflag;

	public UserRoleProductCategoryBranchMapping() {
	}

	public UserRoleProductCategoryBranchMapping(int urpcbid, int urpcid, int bid) {
		this.urpcbid = urpcbid;
		this.urpcid = urpcid;
		this.bid = bid;
	}

	public UserRoleProductCategoryBranchMapping(int urpcbid, int urpcid, int bid, Short editflag, Short deleteflag) {
		this.urpcbid = urpcbid;
		this.urpcid = urpcid;
		this.bid = bid;
		this.editflag = editflag;
		this.deleteflag = deleteflag;
	}
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Id

	@Column(name = "URPCBID", unique = true, nullable = false)
	public int getUrpcbid() {
		return this.urpcbid;
	}

	public void setUrpcbid(int urpcbid) {
		this.urpcbid = urpcbid;
	}

	@Column(name = "URPCID", nullable = false)
	public int getUrpcid() {
		return this.urpcid;
	}

	public void setUrpcid(int urpcid) {
		this.urpcid = urpcid;
	}

	@Column(name = "BID", nullable = false)
	public int getBid() {
		return this.bid;
	}

	public void setBid(int bid) {
		this.bid = bid;
	}

	@Column(name = "EDITFLAG")
	public Short getEditflag() {
		return this.editflag;
	}

	public void setEditflag(Short editflag) {
		this.editflag = editflag;
	}

	@Column(name = "DELETEFLAG")
	public Short getDeleteflag() {
		return this.deleteflag;
	}

	public void setDeleteflag(Short deleteflag) {
		this.deleteflag = deleteflag;
	}

}
