package com.boc.model;
// Generated Nov 17, 2016 3:47:44 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UsrBase generated by hbm2java
 */
@Entity(name="com.boc.model.UsrBase")
@Table(name = "USR_BASE", schema = "WFCONFIG", uniqueConstraints = @UniqueConstraint(columnNames = "NT_ID") )
public class UsrBase implements java.io.Serializable {

	private int uid;
	private BranchBase branchBase;
	private String ntId;
	private String ntDomain;
	private String firstName;
	private String middleName;
	private String lastName;
	private char isActive;
	private Short editflag;
	private Short deleteflag;

	public UsrBase() {
	}

	public UsrBase(int uid, BranchBase branchBase, String ntId, char isActive) {
		this.uid = uid;
		this.branchBase = branchBase;
		this.ntId = ntId;
		this.isActive = isActive;
	}

	public UsrBase(int uid, BranchBase branchBase, String ntId, String ntDomain, String firstName, String middleName,
			String lastName, char isActive, Short editflag,Short deleteflag) {
		this.uid = uid;
		this.branchBase = branchBase;
		this.ntId = ntId;
		this.ntDomain = ntDomain;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.isActive = isActive;
		this.editflag = editflag;
		this.deleteflag = deleteflag;
	}
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Id

	@Column(name = "UID", unique = true, nullable = false)
	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BID", nullable = false)
	public BranchBase getBranchBase() {
		return this.branchBase;
	}

	public void setBranchBase(BranchBase branchBase) {
		this.branchBase = branchBase;
	}

	@Column(name = "NT_ID", unique = true, nullable = false, length = 30)
	public String getNtId() {
		return this.ntId;
	}

	public void setNtId(String ntId) {
		this.ntId = ntId;
	}

	@Column(name = "NT_DOMAIN", length = 30)
	public String getNtDomain() {
		return this.ntDomain;
	}

	public void setNtDomain(String ntDomain) {
		this.ntDomain = ntDomain;
	}

	@Column(name = "FIRST_NAME", length = 50)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "MIDDLE_NAME", length = 50)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "LAST_NAME", length = 50)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "IS_ACTIVE", nullable = false, length = 1)
	public char getIsActive() {
		return this.isActive;
	}

	public void setIsActive(char isActive) {
		this.isActive = isActive;
	}

	@Column(name = "EDITFLAG")
	public Short getEditflag() {
		return this.editflag;
	}

	public void setEditflag(Short editflag) {
		this.editflag = editflag;
	}
	
	@Column(name = "DELETEFLAG")
	public Short getDeleteflag() {
		return this.deleteflag;
	}

	public void setDeleteflag(Short deleteflag) {
		this.deleteflag = deleteflag;
	}

}
