package com.boc.model;
// Generated Sep 27, 2016 11:35:37 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ProvinceBase generated by hbm2java
 */
@Entity
@Table(name = "PROVINCE_BASE", schema = "WFCONFIG", uniqueConstraints = @UniqueConstraint(columnNames = {
		"PROVINCE_CODE", "PROVINCE_NAME" }) )
public class ProvinceBase implements java.io.Serializable {

	private int pid;
	private String provinceCode;
	private String provinceName;
	private Set<ProvinceBranchMapping> provinceBranchMappings = new HashSet<ProvinceBranchMapping>(0);

	public ProvinceBase() {
	}

	public ProvinceBase(int pid, String provinceCode, String provinceName) {
		this.pid = pid;
		this.provinceCode = provinceCode;
		this.provinceName = provinceName;
	}

	public ProvinceBase(int pid, String provinceCode, String provinceName,
			Set<ProvinceBranchMapping> provinceBranchMappings) {
		this.pid = pid;
		this.provinceCode = provinceCode;
		this.provinceName = provinceName;
		this.provinceBranchMappings = provinceBranchMappings;
	}

	@Id

	@Column(name = "PID", unique = true, nullable = false)
	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	@Column(name = "PROVINCE_CODE", nullable = false, length = 50)
	public String getProvinceCode() {
		return this.provinceCode;
	}

	public void setProvinceCode(String provinceCode) {
		this.provinceCode = provinceCode;
	}

	@Column(name = "PROVINCE_NAME", nullable = false, length = 100)
	public String getProvinceName() {
		return this.provinceName;
	}

	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "provinceBase")
	public Set<ProvinceBranchMapping> getProvinceBranchMappings() {
		return this.provinceBranchMappings;
	}

	public void setProvinceBranchMappings(Set<ProvinceBranchMapping> provinceBranchMappings) {
		this.provinceBranchMappings = provinceBranchMappings;
	}

}
