package com.boc.model;
// Generated Nov 17, 2016 3:47:44 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * BranchBase generated by hbm2java
 */
@Entity
@Table(name = "BRANCH_BASE", schema = "WFCONFIG", uniqueConstraints = @UniqueConstraint(columnNames = { "BRANCH_CODE",
		"BRANCH_NAME" }) )
public class BranchBase implements java.io.Serializable {

	private int bid;
	private String branchCode;
	private String branchName;
	private String branchGrade;
	private String branchContactNumber;
	private Short editflag;
	private Set<ProvinceBranchMapping> provinceBranchMappings = new HashSet<ProvinceBranchMapping>(0);
	private Set<UsrBase> usrBases = new HashSet<UsrBase>(0);
	private Set<RlcBranchMapping> rlcBranchMappings = new HashSet<RlcBranchMapping>(0);
	private Set<AreaBranchMapping> areaBranchMappings = new HashSet<AreaBranchMapping>(0);

	public BranchBase() {
	}

	public BranchBase(int bid, String branchCode, String branchName, String branchGrade) {
		this.bid = bid;
		this.branchCode = branchCode;
		this.branchName = branchName;
		this.branchGrade = branchGrade;
	}

	public BranchBase(int bid, String branchCode, String branchName, String branchGrade, String branchContactNumber,
			Short editflag, Set<ProvinceBranchMapping> provinceBranchMappings, Set<UsrBase> usrBases,
			Set<RlcBranchMapping> rlcBranchMappings, Set<AreaBranchMapping> areaBranchMappings) {
		this.bid = bid;
		this.branchCode = branchCode;
		this.branchName = branchName;
		this.branchGrade = branchGrade;
		this.branchContactNumber = branchContactNumber;
		this.editflag = editflag;
		this.provinceBranchMappings = provinceBranchMappings;
		this.usrBases = usrBases;
		this.rlcBranchMappings = rlcBranchMappings;
		this.areaBranchMappings = areaBranchMappings;
	}

	@Id

	@Column(name = "BID", unique = true, nullable = false)
	public int getBid() {
		return this.bid;
	}

	public void setBid(int bid) {
		this.bid = bid;
	}

	@Column(name = "BRANCH_CODE", nullable = false, length = 10)
	public String getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(String branchCode) {
		this.branchCode = branchCode;
	}

	@Column(name = "BRANCH_NAME", nullable = false, length = 50)
	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	@Column(name = "BRANCH_GRADE", nullable = false, length = 20)
	public String getBranchGrade() {
		return this.branchGrade;
	}

	public void setBranchGrade(String branchGrade) {
		this.branchGrade = branchGrade;
	}

	@Column(name = "BRANCH_CONTACT_NUMBER", length = 25)
	public String getBranchContactNumber() {
		return this.branchContactNumber;
	}

	public void setBranchContactNumber(String branchContactNumber) {
		this.branchContactNumber = branchContactNumber;
	}

	@Column(name = "EDITFLAG")
	public Short getEditflag() {
		return this.editflag;
	}

	public void setEditflag(Short editflag) {
		this.editflag = editflag;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "branchBase")
	public Set<ProvinceBranchMapping> getProvinceBranchMappings() {
		return this.provinceBranchMappings;
	}

	public void setProvinceBranchMappings(Set<ProvinceBranchMapping> provinceBranchMappings) {
		this.provinceBranchMappings = provinceBranchMappings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "branchBase")
	public Set<UsrBase> getUsrBases() {
		return this.usrBases;
	}

	public void setUsrBases(Set<UsrBase> usrBases) {
		this.usrBases = usrBases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "branchBase")
	public Set<RlcBranchMapping> getRlcBranchMappings() {
		return this.rlcBranchMappings;
	}

	public void setRlcBranchMappings(Set<RlcBranchMapping> rlcBranchMappings) {
		this.rlcBranchMappings = rlcBranchMappings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "branchBase")
	public Set<AreaBranchMapping> getAreaBranchMappings() {
		return this.areaBranchMappings;
	}

	public void setAreaBranchMappings(Set<AreaBranchMapping> areaBranchMappings) {
		this.areaBranchMappings = areaBranchMappings;
	}

}
