package com.boc.model;
// Generated Jun 10, 2016 11:13:38 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProfessionProductMapping generated by hbm2java
 */
@Entity
@Table(name = "PROFESSION_PRODUCT_MAPPING", schema = "WFCONFIG")
public class ProfessionProductMapping implements java.io.Serializable {

	private int ppid;
	private ProductBase productBase;
	private ProfessionList professionList;

	public ProfessionProductMapping() {
	}

	public ProfessionProductMapping(int ppid, ProductBase productBase, ProfessionList professionList) {
		this.ppid = ppid;
		this.productBase = productBase;
		this.professionList = professionList;
	}

	@Id

	@Column(name = "PPID", unique = true, nullable = false)
	public int getPpid() {
		return this.ppid;
	}

	public void setPpid(int ppid) {
		this.ppid = ppid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_ID", nullable = false)
	public ProductBase getProductBase() {
		return this.productBase;
	}

	public void setProductBase(ProductBase productBase) {
		this.productBase = productBase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROFESSION_ID", nullable = false)
	public ProfessionList getProfessionList() {
		return this.professionList;
	}

	public void setProfessionList(ProfessionList professionList) {
		this.professionList = professionList;
	}

}
