package com.boc.model;
// Generated Sep 27, 2016 11:35:37 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AreaBase generated by hbm2java
 */
@Entity
@Table(name = "AREA_BASE", schema = "WFCONFIG", uniqueConstraints = @UniqueConstraint(columnNames = { "AREA_CODE",
		"AREA_NAME" }) )
public class AreaBase implements java.io.Serializable {

	private int aid;
	private String areaCode;
	private String areaName;
	private Set<AreaBranchMapping> areaBranchMappings = new HashSet<AreaBranchMapping>(0);

	public AreaBase() {
	}

	public AreaBase(int aid, String areaCode, String areaName) {
		this.aid = aid;
		this.areaCode = areaCode;
		this.areaName = areaName;
	}

	public AreaBase(int aid, String areaCode, String areaName, Set<AreaBranchMapping> areaBranchMappings) {
		this.aid = aid;
		this.areaCode = areaCode;
		this.areaName = areaName;
		this.areaBranchMappings = areaBranchMappings;
	}

	@Id

	@Column(name = "AID", unique = true, nullable = false)
	public int getAid() {
		return this.aid;
	}

	public void setAid(int aid) {
		this.aid = aid;
	}

	@Column(name = "AREA_CODE", nullable = false, length = 50)
	public String getAreaCode() {
		return this.areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	@Column(name = "AREA_NAME", nullable = false, length = 100)
	public String getAreaName() {
		return this.areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "areaBase")
	public Set<AreaBranchMapping> getAreaBranchMappings() {
		return this.areaBranchMappings;
	}

	public void setAreaBranchMappings(Set<AreaBranchMapping> areaBranchMappings) {
		this.areaBranchMappings = areaBranchMappings;
	}

}
