package com.boc.model;
// Generated Jun 23, 2016 11:37:27 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductSecurityTypeMapping generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT_SECURITY_TYPE_MAPPING", schema = "WFCONFIG")
public class ProductSecurityTypeMapping implements java.io.Serializable {

	private int pstid;
	private ProductBase productBase;
	private SecurityTypeBase securityTypeBase;

	public ProductSecurityTypeMapping() {
	}

	public ProductSecurityTypeMapping(int pstid, ProductBase productBase, SecurityTypeBase securityTypeBase) {
		this.pstid = pstid;
		this.productBase = productBase;
		this.securityTypeBase = securityTypeBase;
	}

	@Id

	@Column(name = "PSTID", unique = true, nullable = false)
	public int getPstid() {
		return this.pstid;
	}

	public void setPstid(int pstid) {
		this.pstid = pstid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_ID", nullable = false)
	public ProductBase getProductBase() {
		return this.productBase;
	}

	public void setProductBase(ProductBase productBase) {
		this.productBase = productBase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SECURITY_TYPE_ID", nullable = false)
	public SecurityTypeBase getSecurityTypeBase() {
		return this.securityTypeBase;
	}

	public void setSecurityTypeBase(SecurityTypeBase securityTypeBase) {
		this.securityTypeBase = securityTypeBase;
	}

}
