package com.boc.model;
// Generated Jul 29, 2016 11:14:54 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * RlcBase generated by hbm2java
 */
@Entity
@Table(name = "RLC_BASE", schema = "WFCONFIG", uniqueConstraints = @UniqueConstraint(columnNames = { "RLC_CODE",
		"RLC_NAME" }) )
public class RlcBase implements java.io.Serializable {

	private int rlcId;
	private String rlcCode;
	private String rlcName;
	private Set<RlcBranchMapping> rlcBranchMappings = new HashSet<RlcBranchMapping>(0);

	public RlcBase() {
	}

	public RlcBase(int rlcId, String rlcCode, String rlcName) {
		this.rlcId = rlcId;
		this.rlcCode = rlcCode;
		this.rlcName = rlcName;
	}

	public RlcBase(int rlcId, String rlcCode, String rlcName, Set<RlcBranchMapping> rlcBranchMappings) {
		this.rlcId = rlcId;
		this.rlcCode = rlcCode;
		this.rlcName = rlcName;
		this.rlcBranchMappings = rlcBranchMappings;
	}

	@Id

	@Column(name = "RLC_ID", unique = true, nullable = false)
	public int getRlcId() {
		return this.rlcId;
	}

	public void setRlcId(int rlcId) {
		this.rlcId = rlcId;
	}

	@Column(name = "RLC_CODE", nullable = false, length = 10)
	public String getRlcCode() {
		return this.rlcCode;
	}

	public void setRlcCode(String rlcCode) {
		this.rlcCode = rlcCode;
	}

	@Column(name = "RLC_NAME", nullable = false, length = 50)
	public String getRlcName() {
		return this.rlcName;
	}

	public void setRlcName(String rlcName) {
		this.rlcName = rlcName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rlcBase")
	public Set<RlcBranchMapping> getRlcBranchMappings() {
		return this.rlcBranchMappings;
	}

	public void setRlcBranchMappings(Set<RlcBranchMapping> rlcBranchMappings) {
		this.rlcBranchMappings = rlcBranchMappings;
	}

}
